Parameters:
  App:
    Type: String
    Description: Your application's name.
    Default: 'timerservice'
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
    Default: 'dev'

Resources:
  TimerServiceEcsSecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      Description: 'Allow connections from the API-GW VPCLink to port 8080.'
      IpProtocol: tcp
      CidrIp: '10.0.0.0/16'
      FromPort: 8080
      ToPort: 8080
      GroupId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-EnvironmentSecurityGroup'

